export interface IMenuItem {
  id: number;
  title: string;
  // 0目录、1菜单、2权限按钮
  type: number;
  path?: string;
  parentId?: number | null;
  levelPath?: string;
  key?: Nullable<string>;
  icon?: Nullable<string>;
  children?: IMenuItem[];
  // 是否为首页,仅在menu类型为1时生效
  home?: boolean;
}

export const menus: IMenuItem[] = [
  {
    id: 1,
    title: 'Dashboard',
    type: 1,
    path: '/',
    parentId: null,
    levelPath: '1',
    key: null,
    icon: 'apps-line',
    children: [
      {
        id: 11,
        title: '分析页',
        path: '/dashboard/analysis',
        type: 2,
        parentId: 1,
        levelPath: '1-11',
        home: true,
      },
      {
        id: 12,
        title: '工作台',
        path: '/dashboard/workbench',
        type: 2,
        parentId: 1,
        levelPath: '1-12',
      },
      {
        id: 13,
        title: '监控页',
        path: '/dashboard/monitor',
        type: 2,
        parentId: 1,
        levelPath: '1-13',
      },
      {
        id: 14,
        title: '我的任务',
        path: '/dashboard/task',
        type: 2,
        parentId: 1,
        levelPath: '1-14',
      },
    ],
  },
  {
    id: 2,
    title: '权限管理',
    type: 1,
    path: '',
    parentId: null,
    levelPath: '2',
    key: null,
    icon: 'apps-line',
    children: [],
  },
  {
    id: 3,
    title: '组件',
    type: 1,
    path: '/',
    parentId: null,
    levelPath: '3',
    key: null,
    icon: 'apps-line',
    children: [
      {
        id: 333331111111,
        title: 'Authority',
        type: 2,
        path: '/comp/authority',
        parentId: 3,
        levelPath: '3-333331111111',
        key: null,
        icon: 'apps-line',
        children: [],
      },
      {
        id: 31,
        title: 'Button',
        type: 2,
        path: '/comp/button',
        parentId: 3,
        levelPath: '3-31',
        key: null,
        icon: 'apps-line',
        children: [],
      },
      {
        id: 32,
        title: 'Watermark',
        type: 2,
        path: '/comp/watermark',
        parentId: 3,
        levelPath: '3-32',
        key: null,
        icon: 'apps-line',
        children: [],
      },
      {
        id: 33,
        title: 'ScrollBar',
        type: 2,
        path: '/comp/scrollBar',
        parentId: 3,
        levelPath: '3-33',
        key: null,
        icon: 'apps-line',
        children: [],
      },
      {
        id: 34,
        title: 'Table',
        type: 2,
        path: '/comp/table',
        parentId: 3,
        levelPath: '3-34',
        key: null,
        icon: 'apps-line',
        children: [],
      },
      {
        id: 35,
        title: 'Form',
        type: 2,
        path: '/comp/form',
        parentId: 3,
        levelPath: '3-35',
        key: null,
        icon: 'apps-line',
        children: [],
      },
      {
        id: 36,
        title: 'Highlight',
        type: 2,
        path: '/comp/highlight',
        parentId: 3,
        levelPath: '3-36',
        key: null,
        icon: 'apps-line',
        children: [],
      },
      {
        id: 37,
        title: 'Example',
        type: 2,
        path: '/comp/example',
        parentId: 3,
        levelPath: '3-37',
        key: null,
        icon: 'apps-line',
        children: [],
      },
      {
        id: 38,
        title: 'VirtualList',
        type: 2,
        path: '/comp/virtualList',
        parentId: 3,
        levelPath: '3-38',
        key: null,
        icon: 'apps-line',
        children: [],
      },
      {
        id: 39,
        title: 'View',
        type: 2,
        path: '/comp/view',
        parentId: 3,
        levelPath: '3-39',
        key: null,
        icon: 'apps-line',
        children: [],
      },
      {
        id: 3999991,
        title: 'loading',
        type: 2,
        path: '/comp/loading',
        parentId: 3,
        levelPath: '3-3999991',
        key: null,
        icon: 'apps-line',
        children: [],
      },
      {
        id: 3999992,
        title: 'contextMenu',
        type: 2,
        path: '/comp/contextMenu',
        parentId: 3,
        levelPath: '3-3999992',
        key: null,
        icon: 'apps-line',
        children: [],
      },
      {
        id: 3999992111,
        title: 'IconSelector',
        type: 2,
        path: '/comp/iconSelector',
        parentId: 3,
        levelPath: '3-3999992111',
        key: null,
        icon: 'apps-line',
        children: [],
      },
      {
        id: 3999992112,
        title: 'InfiniteScroll',
        type: 2,
        path: '/comp/infiniteScroll',
        parentId: 3,
        levelPath: '3-3999992112',
        key: null,
        icon: 'apps-line',
        children: [],
      },
      {
        id: 3999992113,
        title: 'Timestamp',
        type: 2,
        path: '/comp/timestamp',
        parentId: 3,
        levelPath: '3-3999992113',
        key: null,
        icon: 'apps-line',
        children: [],
      },
      {
        id: 11121992113,
        title: '富文本编辑器',
        type: 1,
        path: '/comp/timestamp',
        parentId: 3,
        levelPath: '3-11121992113',
        key: null,
        icon: 'apps-line',
        children: [
          {
            id: 2221992113,
            title: '富文本编辑器',
            type: 1,
            path: '/comp/aiEditor',
            parentId: 3,
            levelPath: '3-11121992113-2221992113',
            key: null,
            icon: 'apps-line',
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: 4,
    title: 'Hooks',
    type: 1,
    path: '',
    parentId: null,
    levelPath: '4',
    key: null,
    icon: 'apps-line',
    children: [
      {
        id: 41,
        title: 'useClickOutside',
        type: 2,
        path: '/hooks/clickOutside',
        parentId: 4,
        levelPath: '4-41',
        key: null,
        icon: 'apps-line',
      },
    ],
  },
  {
    id: 5,
    title: 'Exception',
    type: 1,
    path: '5',
    parentId: null,
    levelPath: '4',
    key: null,
    icon: 'apps-line',
    children: [
      {
        id: 51,
        title: '200(Ok)',
        type: 2,
        path: '/exception/ok',
        parentId: 5,
        levelPath: '5-51',
        key: null,
        icon: 'apps-line',
      },
      {
        id: 52,
        title: '401(Unauthorized)',
        type: 2,
        path: '/exception/unauthorized',
        parentId: 5,
        levelPath: '5-52',
        key: null,
        icon: 'apps-line',
      },
      {
        id: 53,
        title: '403(Forbidden)',
        type: 2,
        path: '/exception/forbidden',
        parentId: 5,
        levelPath: '5-53',
        key: null,
        icon: 'apps-line',
      },
      {
        id: 54,
        title: '404(NotFound)',
        type: 2,
        path: '/exception/notFound',
        parentId: 5,
        levelPath: '5-54',
        key: null,
        icon: 'apps-line',
      },
      {
        id: 55,
        title: '500(ServerError)',
        type: 2,
        path: '/exception/serverError',
        parentId: 5,
        levelPath: '5-55',
        key: null,
        icon: 'apps-line',
      },
    ],
  },
];
